# Cadastrar usuário: 
# Recebe nome, email e senha 
# Devolve token de autorização 
POST http://localhost:3003/signup 
Content-Type: application/json

{
"name": "teste1", "email": "teste1@email.com", "password": "123456"
}

###

# Login: 
# Recebe email e senha 
# Devolve token de autorização 
POST http://localhost:3003/login 
Content-Type: application/json

{
"email": "teste1@email.com", "password": "123456"
}

###

# Fazer amizade: 
# Recebe token de autorização e id do usuário que será adicionado à lista de amigos 
# Devolve mensagem de sucesso 
POST http://localhost:3003/add/95809bc9-28b5-4c75-95de-17d882e203c7 
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjUyZDY1M2YwLTVhNWUtNDc4ZS04MzRlLWQ0OGNhNmQ0ODk3MiIsImlhdCI6MTY2MDI2MzgwNywiZXhwIjoxNjYwMzUwMjA3fQ.B5YZ4pVcAkIlwBE3F8JJ2gfMsyyP6K2a_oM6AxZ7xj0
Content-Type: application/json

###
# Desfazer amizade: 
# Recebe token de autorização e id do usuário que será removido da lista de amigos 
# Devolve mensagem de sucesso 
DELETE http://localhost:3003/unfriend/95809bc9-28b5-4c75-95de-17d882e203c7
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjUyZDY1M2YwLTVhNWUtNDc4ZS04MzRlLWQ0OGNhNmQ0ODk3MiIsImlhdCI6MTY2MDI2MzgwNywiZXhwIjoxNjYwMzUwMjA3fQ.B5YZ4pVcAkIlwBE3F8JJ2gfMsyyP6K2a_oM6AxZ7xj0
Content-Type: application/json

###

# Ver o feed com paginação de 5 posts por página:
# Recebe token de autorização e tem opção de receber o número da página do feed 
# Devolve informações dos posts dos amigos do usuário 
GET http://localhost:3003/feed?page=2 
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjUyZDY1M2YwLTVhNWUtNDc4ZS04MzRlLWQ0OGNhNmQ0ODk3MiIsImlhdCI6MTY2MDI2MzgwNywiZXhwIjoxNjYwMzUwMjA3fQ.B5YZ4pVcAkIlwBE3F8JJ2gfMsyyP6K2a_oM6AxZ7xj0
Content-Type: application/json

###

# Ver apenas um tipo de post do feed: 
# Recebe token de autorização e o tipo de post 
# Devolve informações de todos os posts com o tipo passado 
GET http://localhost:3003/feed/normal 
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjUyZDY1M2YwLTVhNWUtNDc4ZS04MzRlLWQ0OGNhNmQ0ODk3MiIsImlhdCI6MTY2MDI2MzgwNywiZXhwIjoxNjYwMzUwMjA3fQ.B5YZ4pVcAkIlwBE3F8JJ2gfMsyyP6K2a_oM6AxZ7xj0
Content-Type: application/json

###

# Buscar um post por id: 
# Recebe token de autorização e id do post 
# Devolve id do post, foto, descrição, data de criação e tipo 
GET http://localhost:3003/post/0ce7301a-b8b6-4945-891e-bb7120f4bef5
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjUyZDY1M2YwLTVhNWUtNDc4ZS04MzRlLWQ0OGNhNmQ0ODk3MiIsImlhdCI6MTY2MDI2MzgwNywiZXhwIjoxNjYwMzUwMjA3fQ.B5YZ4pVcAkIlwBE3F8JJ2gfMsyyP6K2a_oM6AxZ7xj0
Content-Type: application/json

###

# Criar post: 
# Recebe token de autorização, foto, descrição e tipo 
# Devolve mensagem de sucesso 
POST http://localhost:3003/post 
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjUyZDY1M2YwLTVhNWUtNDc4ZS04MzRlLWQ0OGNhNmQ0ODk3MiIsImlhdCI6MTY2MDI2MzgwNywiZXhwIjoxNjYwMzUwMjA3fQ.B5YZ4pVcAkIlwBE3F8JJ2gfMsyyP6K2a_oM6AxZ7xj0
Content-Type: application/json

{
"photo": "urlDaFoto", "description": "Foto do meu cachorro!", "type": "Normal"
}

###

# Comentar no post: 
# Recebe token de autorização, id do post e comentário 
# Devolve mensagem de sucesso 

POST http://localhost:3003/comment/0ce7301a-b8b6-4945-891e-bb7120f4bef5 
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjUyZDY1M2YwLTVhNWUtNDc4ZS04MzRlLWQ0OGNhNmQ0ODk3MiIsImlhdCI6MTY2MDI2MzgwNywiZXhwIjoxNjYwMzUwMjA3fQ.B5YZ4pVcAkIlwBE3F8JJ2gfMsyyP6K2a_oM6AxZ7xj0
Content-Type: application/json

{
"comment": "Que lindo!"
}

###

# Curtir post: 
# Recebe token de autorização e id do post 
# Devolve mensagem de sucesso
POST http://localhost:3003/post/0ce7301a-b8b6-4945-891e-bb7120f4bef5 
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjUyZDY1M2YwLTVhNWUtNDc4ZS04MzRlLWQ0OGNhNmQ0ODk3MiIsImlhdCI6MTY2MDI2MzgwNywiZXhwIjoxNjYwMzUwMjA3fQ.B5YZ4pVcAkIlwBE3F8JJ2gfMsyyP6K2a_oM6AxZ7xj0
Content-Type: application/json

###

# Descurtir post: 
# Recebe token de autorização e id do post 
# Devolve mensagem de sucesso 
PUT http://localhost:3003/post/0ce7301a-b8b6-4945-891e-bb7120f4bef5 
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjUyZDY1M2YwLTVhNWUtNDc4ZS04MzRlLWQ0OGNhNmQ0ODk3MiIsImlhdCI6MTY2MDI2MzgwNywiZXhwIjoxNjYwMzUwMjA3fQ.B5YZ4pVcAkIlwBE3F8JJ2gfMsyyP6K2a_oM6AxZ7xj0
Content-Type: application/json

###